# Generated by Django 5.2.6 on 2025-09-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": (
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                )
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship_app.author",
            ),
        ),
    ]
